# Keep this file in the directory you are running netdaemon from.

ssh:
    username: jamesbond
    password: strongpassword

subnet: 192.168.0.1/24

admin-email: moneypenny@hmss.uk

smtp:
    host: smtp.hmss.uk
    port: 007
    id: jamesbond@hmss.uk
    password: iamnotpiercebrosnan
    
verbose: true 
